name: HeroesHUD
version: 1.5.2
main: me.Drehverschluss.HeroesHUD.HeroesHUD
depend: [ Heroes,Spout ]
commands:
    csg:
        description: Opens a very special selection Menu for Heroes
        usage: /<command>