name: HeroesHUD
version: 1.5
main: me.Drehverschluss.HeroesHUD.HeroesHUD
depend: [ Heroes,Spout ]
commands:
    hsg:
        description: Opens a very special selection Menu for Heroes
        usage: /<command>