name: HeroesHUD
version: 1.5.1
main: me.Drehverschluss.HeroesHUD.HeroesHUD
depend: [ Heroes,Spout ]
commands:
    cs:
        description: Opens a very special selection Menu for Heroes
        usage: /<command>